name: Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Run API
    runs-on: ubuntu-latest #1
    steps:
      - name: Build API
        run: |
          echo "Build API"
          sleep 10s
