# This is a basic workflow to help you get started with Actions

name: Scheduler Cron Job
on:
  schedule:
    - cron:  '*/1 * * * *'    # At every 1 minute
  

jobs:
  singleJobName:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.DELAYED_JOB_CHECKOUT_REF }} # SHA that triggered your original job 

      - name: Do some work
        run: echo $GITHUB_SHA
